export enum District {
	BLACK_RIVER = "BLACK_RIVER",
	FLACQ = "FLACQ",
	GRAND_PORT = "GRAND_PORT",
	MOKA = "MOKA",
	PAMPLEMOUSSES = "PAMPLEMOUSSES",
	PLAINES_WILHEMS = "PLAINES_WILHEMS",
	PORT_LOUIS = "PORT_LOUIS",
	RIVIERE_DU_REMPART = "RIVIERE_DU_REMPART",
	SAVANNE = "SAVANNE",
	RODRIGUES = "RODRIGUES",
}
