import {DropDownValue} from "../models/drop-down-value.model";

export const DROP_DOWN_VALUE = [
	{ id: 1, name: "Angive", value: "Angive"},
	{ id: 2, name: "Arouille", value: "Arouille"},
	{ id: 4, name: "Betrave", value: "Betrave"},
	{ id: 5, name: "Brede Baton Blanc" , value: "Brede Baton Blanc"},
	{ id: 6, name: "Brede Baton Vert" , value: "Brede Vert"},
	{ id: 7, name: "Brede Chouchou" , value: "Brede Chouchou"},
	{ id: 8, name: "Brede de Chine" , value: "Brede de Chine"},
	{ id: 9, name: "Brede Giraumon" , value: "Brede Giraumon"},
	{ id: 10, name: "Brede National" , value: "Brede National"},
	{ id: 11, name: "Brede Songe" , value: "Brede Songe"},
	{ id: 12, name: "Brede Souflet" , value: "Brede Souflet"},
	{ id: 13, name: "Brede Tom Pouce" , value: "Brede Tom Pouce"},
	{ id: 14, name: "Bringelle (Long)" , value: "Bringelle (Long)"},
	{ id: 15, name: "Bringelle (Rond)" , value: "Bringelle (Rond)"},
	{ id: 16, name: "Broccoli" , value: "Broccoli"},
	{ id: 17, name: "Butternut" , value: "Butternut"},
	{ id: 18, name: "Calebasse" , value: "Calebasse"},
	{ id: 19, name: "Calebasse chinois" , value: "Calebasse chinois"},
	{ id: 20, name: "Carotte" , value: "Carotte"},
	{ id: 21, name: "Carry Poulet" , value: "Carry Poulet"},
	{ id: 22, name: "Celery" , value: "Celery"},
	{ id: 23, name: "Cherry" , value: "Cherry"},
	{ id: 24, name: "Chou (Mauve)" , value: "Chou (Mauve)"},
	{ id: 25, name: "Chou (Vert)" , value: "Chou (Vert)"},
	{ id: 26, name: "Chouchou" , value: "Chouchou"},
	{ id: 27, name: "Chou-fleur" , value: "Chou-fleur"},
	{ id: 28, name: "Concombre" , value: "Concombre"},
	{ id: 29, name: "Concombre (Vert)" , value: "Concombre (Vert)"},
	{ id: 30, name: "Cotomili" , value: "Cotomili"},
	{ id: 31, name: "Courgette" , value: "Courgette"},
	{ id: 32, name: "Cresson" , value: "Cresson"},
	{ id: 33, name: "Fleur Onion" , value: "Fleur Onion"},
	{ id: 34, name: "Fruit a Pain" , value: "Fruit a Pain"},
	{ id: 35, name: "Gingembre" , value: "Gingembre"},
	{ id: 36, name: "Giraumon" , value: "Giraumon"},
	{ id: 37, name: "Gros Piment" , value: "Gros Piment"},
	{ id: 38, name: "Gros Pois" , value: "Gros Pois"},
	{ id: 39, name: "Haricot" , value: "Haricot"},
	{ id: 40, name: "Laitue" , value: "Laitue"},
	{ id: 41, name: "Lalo" , value: "Lalo"},
	{ id: 42, name: "La Menthe" , value: "La Menthe"},
	{ id: 43, name: "Laque Onion" , value: "Laque Onion"},
	{ id: 44, name: "Laque Ail" , value: "Laque Ail"},
	{ id: 45, name: "Lepois Carré" , value: "Lepois Carré"},
	{ id: 46, name: "Mais" , value: "Mais"},
	{ id: 47, name: "Manioc" , value: "Manioc"},
	{ id: 48, name: "Margoze" , value: "Margoze"},
	{ id: 49, name: "Oignon" , value: "Oignon"},
	{ id: 50, name: "Patate" , value: "Patate"},
	{ id: 51, name: "Patate Chinois" , value: "Patate Chinois"},
	{ id: 52, name: "Patole" , value: "Patole"},
	{ id: 53, name: "Patisson" , value: "Patisson"},
	{ id: 54, name: "Persi" , value: "Persi"},
	{ id: 55, name: "Petsai" , value: "Petsai"},
	{ id: 56, name: "Piment Cabri" , value: "Piment Cabri"},
	{ id: 57, name: "Piment Carry" , value: "Piment Carry"},
	{ id: 58, name: "Pipengaille" , value: "Pipengaille"},
	{ id: 59, name: "Pistache" , value: "Pistache"},
	{ id: 60, name: "Poireau" , value: "Poireau"},
	{ id: 61, name: "Poivron (Jaune)" , value: "Poivron (Jaune)"},
	{ id: 62, name: "Turnip" , value: "Turnip"},
	{ id: 63, name: "Poivron (Rouge)" , value: "Poivron (Rouge)"},
	{ id: 64, name: "Poivron (Vert)" , value: "Poivron (Vert)"},
	{ id: 65, name: "Pomme d'Amour (Terre)" , value: "Pomme d'Amour (Terre)"},
	{ id: 66, name: "Pomme d'Amour (Serre)" , value: "Pomme d'Amour (Serre)"},
	{ id: 67, name: "Pomme de terre" , value: "Pomme de terre"},
	{ id: 68, name: "Radis" , value: "Radis"},
	{ id: 69, name: "Rave" , value: "Rave"},
	{ id: 70, name: "Romarin" , value: "Romarin"},
	{ id: 71, name: "Safron" , value: "Safron"},
	{ id: 72, name: "Sans Fils (Haricot)" , value: "Sans Fils (Haricot)"},
	{ id: 73, name: "Sooran" , value: "Sooran"},
	{ id: 74, name: "Thyme" , value: "Thyme"},
	{ id: 75, name: "Ti Piment" , value: "Ti Piment"},
	{ id: 76, name: "Ti Pois" , value: "Ti Pois"},
	{ id: 77, name: "Tomate" , value: "Tomate"},
	{ id: 78, name: "Violette" , value: "Violette"},
	{ id: 79, name: "Voem", value: "Voem" }
] as DropDownValue[];

export const DROP_DOWN_VALUE_V2 = [
	{ id: 1, name: "Angive", value: "Angive" },
	{ id: 2, name: "Arouille", value: "Arouille" },
	{ id: 3, name: "Basilc", value: "Basilc" },
	{ id: 4, name: "Betrave", value: "Betrave" },
	{ id: 5, name: "Brede Baton Blanc", value: "Brede Baton Blanc" },
	{ id: 6, name: "Brede Baton Vert", value: "Brede Baton Vert" },
	{ id: 7, name: "Brede Chouchou", value: "Brede Chouchou" },
	{ id: 8, name: "Brede de Chine", value: "Brede de Chine" },
	{ id: 9, name: "Brede Epinard", value: "Brede Epinard" },
	{ id: 10, name: "Brede Giraumon", value: "Brede Giraumon" },
	{ id: 11, name: "Brede National", value: "Brede National" },
	{ id: 12, name: "Brede Songe", value: "Brede Songe" },
	{ id: 13, name: "Brede Souflet", value: "Brede Souflet" },
	{ id: 14, name: "Brede Tom Pouce", value: "Brede Tom Pouce" },
	{ id: 15, name: "Bringelle (Long)", value: "Bringelle (Long)" },
	{ id: 16, name: "Bringelle (Rond)", value: "Bringelle (Rond)" },
	{ id: 17, name: "Broccoli", value: "Broccoli" },
	{ id: 18, name: "Butternut", value: "Butternut" },
	{ id: 19, name: "Calebasse", value: "Calebasse" },
	{ id: 20, name: "calebasse chinois", value: "calebasse chinois" },
	{ id: 21, name: "Carotte", value: "Carotte" },
	{ id: 22, name: "Carry Poulet", value: "Carry Poulet" },
	{ id: 23, name: "Celery", value: "Celery" },
	{ id: 24, name: "Chou (Mauve)", value: "Chou (Mauve)" },
	{ id: 25, name: "Chou (Vert)", value: "Chou (Vert)" },
	{ id: 26, name: "Chouchou", value: "Chouchou" },
	{ id: 27, name: "Chou-fleur", value: "Chou-fleur" },
	{ id: 28, name: "Concombre", value: "Concombre" },
	{ id: 29, name: "Concombre (Vert)", value: "Concombre (Vert)" },
	{ id: 30, name: "Cotomili", value: "Cotomili" },
	{ id: 31, name: "Courgette", value: "Courgette" },
	{ id: 32, name: "Cresson", value: "Cresson" },
	{ id: 33, name: "Fleur Onion", value: "Fleur Onion" },
	{ id: 34, name: "Fruit a Pain", value: "Fruit a Pain" },
	{ id: 35, name: "Garlic (IMP)", value: "Garlic (IMP)" },
	{ id: 36, name: "Garlic (loc)", value: "Garlic (loc)" },
	{ id: 37, name: "Gingembre", value: "Gingembre" },
	{ id: 38, name: "Giraumon", value: "Giraumon" },
	{ id: 39, name: "Gros Piment", value: "Gros Piment" },
	{ id: 40, name: "Haricot", value: "Haricot" },
	{ id: 41, name: "La Menthe", value: "La Menthe" },
	{ id: 42, name: "Laitue", value: "Laitue" },
	{ id: 43, name: "Lalo", value: "Lalo" },
	{ id: 44, name: "Laque Ail", value: "Laque Ail" },
	{ id: 45, name: "Laque Onion", value: "Laque Onion" },
	{ id: 46, name: "Lepois Carré", value: "Lepois Carré" },
	{ id: 47, name: "Mais", value: "Mais" },
	{ id: 48, name: "Manioc", value: "Manioc" },
	{ id: 49, name: "Margoze", value: "Margoze" },
	{ id: 50, name: "Onion (IMP)", value: "Onion (IMP)" },
	{ id: 51, name: "Onion (LOC Toupi)", value: "Onion (LOC Toupi)" },
	{ id: 52, name: "Onion (LOC HY)", value: "Onion (LOC HY)" },
	{ id: 53, name: "Patate", value: "Patate" },
	{ id: 54, name: "Patisson", value: "Patisson" },
	{ id: 55, name: "Patole", value: "Patole" },
	{ id: 56, name: "Persi", value: "Persi" },
	{ id: 57, name: "Petsai", value: "Petsai" },
	{ id: 58, name: "Piment Cabri", value: "Piment Cabri" },
	{ id: 59, name: "Piment Carry", value: "Piment Carry" },
	{ id: 60, name: "Pipengaille", value: "Pipengaille" },
	{ id: 61, name: "Pistache", value: "Pistache" },
	{ id: 62, name: "Poireau", value: "Poireau" },
	{ id: 63, name: "Poivron (Jaune)", value: "Poivron (Jaune)" },
	{ id: 64, name: "Poivron (Rouge)", value: "Poivron (Rouge)" },
	{ id: 65, name: "Poivron (Vert)", value: "Poivron (Vert)" },
	{ id: 66, name: "Pomme D'amour (Terre)", value: "Pomme D'amour (Terre)" },
	{ id: 67, name: "Pomme d'Amour (Serre)", value: "Pomme d'Amour (Serre)" },
	{ id: 68, name: "Pomme de terre (IMP)", value: "Pomme de terre (IMP)" },
	{ id: 69, name: "Pomme de terre (LOC)", value: "Pomme de terre (LOC)" },
	{ id: 70, name: "Radis", value: "Radis" },
	{ id: 71, name: "Rave", value: "Rave" },
	{ id: 72, name: "Romarin", value: "Romarin" },
	{ id: 73, name: "Safron", value: "Safron" },
	{ id: 74, name: "Sooran", value: "Sooran" },
	{ id: 75, name: "Thyme", value: "Thyme" },
	{ id: 76, name: "Ti Piment", value: "Ti Piment" },
	{ id: 77, name: "Tomate", value: "Tomate" },
	{ id: 78, name: "Tomato ( Cherry)", value: "Tomato ( Cherry)" },
	{ id: 79, name: "Turnip", value: "Turnip" },
	{ id: 80, name: "Violette", value: "Violette" },
	{ id: 81, name: "Voem", value: "Voem" }
] as DropDownValue[];
