import {DropDownValue} from "../models/drop-down-value.model";

export const DROP_DOWN_VALUE = [
	{ id: 1, name: "Angive", type: "VEGETABLE" },
	{ id: 2, name: "Arouille", type: "VEGETABLE"},
	{ id: 4, name: "Betrave", type: "VEGETABLE"},
	{ id: 5, name: "Brede Baton Blanc" , type: "VEGETABLE"},
	{ id: 6, name: "Brede Baton Vert" , type: "VEGETABLE"},
	{ id: 7, name: "Brede Chouchou" , type: "VEGETABLE"},
	{ id: 8, name: "Brede de Chine" , type: "VEGETABLE"},
	{ id: 9, name: "Brede Giraumon" , type: "VEGETABLE"},
	{ id: 10, name: "Brede National" , type: "VEGETABLE"},
	{ id: 11, name: "Brede Songe" , type: "VEGETABLE"},
	{ id: 12, name: "Brede Souflet" , type: "VEGETABLE"},
	{ id: 13, name: "Brede Tom Pouce" , type: "VEGETABLE"},
	{ id: 14, name: "Bringelle (Long)" , type: "VEGETABLE"},
	{ id: 15, name: "Bringelle (Rond)" , type: "VEGETABLE"},
	{ id: 16, name: "Broccoli" , type: "VEGETABLE"},
	{ id: 17, name: "Butternut" , type: "VEGETABLE"},
	{ id: 18, name: "Calebasse" , type: "VEGETABLE"},
	{ id: 19, name: "Calebasse chinois" , type: "VEGETABLE"},
	{ id: 20, name: "Carotte" , type: "VEGETABLE"},
	{ id: 21, name: "Carry Poulet" , type: "VEGETABLE"},
	{ id: 22, name: "Celery" , type: "VEGETABLE"},
	{ id: 23, name: "Cherry" , type: "VEGETABLE"},
	{ id: 24, name: "Chou (Mauve)" , type: "VEGETABLE"},
	{ id: 25, name: "Chou (Vert)" , type: "VEGETABLE"},
	{ id: 26, name: "Chouchou" , type: "VEGETABLE"},
	{ id: 27, name: "Chou-fleur" , type: "VEGETABLE"},
	{ id: 28, name: "Concombre" , type: "VEGETABLE"},
	{ id: 29, name: "Concombre (Vert)" , type: "VEGETABLE"},
	{ id: 30, name: "Cotomili" , type: "VEGETABLE"},
	{ id: 31, name: "Courgette" , type: "VEGETABLE"},
	{ id: 32, name: "Cresson" , type: "VEGETABLE"},
	{ id: 33, name: "Fleur Onion" , type: "VEGETABLE"},
	{ id: 34, name: "Fruit a Pain" , type: "VEGETABLE"},
	{ id: 35, name: "Gingembre" , type: "VEGETABLE"},
	{ id: 36, name: "Giraumon" , type: "VEGETABLE"},
	{ id: 37, name: "Gros Piment" , type: "VEGETABLE"},
	{ id: 38, name: "Gros Pois" , type: "VEGETABLE"},
	{ id: 39, name: "Haricot" , type: "VEGETABLE"},
	{ id: 40, name: "Laitue" , type: "VEGETABLE"},
	{ id: 41, name: "Lalo" , type: "VEGETABLE"},
	{ id: 42, name: "La Menthe" , type: "VEGETABLE"},
	{ id: 43, name: "Laque Onion" , type: "VEGETABLE"},
	{ id: 44, name: "Laque Ail" , type: "VEGETABLE"},
	{ id: 45, name: "Lepois Carré" , type: "VEGETABLE"},
	{ id: 46, name: "Mais" , type: "VEGETABLE"},
	{ id: 47, name: "Manioc" , type: "VEGETABLE"},
	{ id: 48, name: "Margoze" , type: "VEGETABLE"},
	{ id: 49, name: "Oignon" , type: "VEGETABLE"},
	{ id: 50, name: "Patate" , type: "VEGETABLE"},
	{ id: 51, name: "Patate Chinois" , type: "VEGETABLE"},
	{ id: 52, name: "Patole" , type: "VEGETABLE"},
	{ id: 53, name: "Patisson" , type: "VEGETABLE"},
	{ id: 54, name: "Persi" , type: "VEGETABLE"},
	{ id: 55, name: "Petsai" , type: "VEGETABLE"},
	{ id: 56, name: "Piment Cabri" , type: "VEGETABLE"},
	{ id: 57, name: "Piment Carry" , type: "VEGETABLE"},
	{ id: 58, name: "Pipengaille" , type: "VEGETABLE"},
	{ id: 59, name: "Pistache" , type: "VEGETABLE"},
	{ id: 60, name: "Poireau" , type: "VEGETABLE"},
	{ id: 61, name: "Poivron (Jaune)" , type: "VEGETABLE"},
	{ id: 62, name: "Turnip" , type: "VEGETABLE"},
	{ id: 63, name: "Poivron (Rouge)" , type: "VEGETABLE"},
	{ id: 64, name: "Poivron (Vert)" , type: "VEGETABLE"},
	{ id: 65, name: "Pomme d'Amour (Terre)" , type: "VEGETABLE"},
	{ id: 66, name: "Pomme d'Amour (Serre)" , type: "VEGETABLE"},
	{ id: 67, name: "Pomme de terre" , type: "VEGETABLE"},
	{ id: 68, name: "Radis" , type: "VEGETABLE"},
	{ id: 69, name: "Rave" , type: "VEGETABLE"},
	{ id: 70, name: "Romarin" , type: "VEGETABLE"},
	{ id: 71, name: "Safron" , type: "VEGETABLE"},
	{ id: 72, name: "Sans Fils (Haricot)" , type: "VEGETABLE"},
	{ id: 73, name: "Sooran" , type: "VEGETABLE"},
	{ id: 74, name: "Thyme" , type: "VEGETABLE"},
	{ id: 75, name: "Ti Piment" , type: "VEGETABLE"},
	{ id: 76, name: "Ti Pois" , type: "VEGETABLE"},
	{ id: 77, name: "Tomate" , type: "VEGETABLE"},
	{ id: 78, name: "Violette" , type: "VEGETABLE"},
	{ id: 79, name: "Voem", type: "VEGETABLE" }
] as DropDownValue[];
